### ISSUE TITLE
Include xpress solver default settings in config/default.yaml

### ISSUE THREAD

**Issue by pworschischek-aggmag** [PyPSA/PyPSA#1230]
linopy already interfaces the FICO Xpress solver and may be activated by
```
solver:
  name: xpress
```

However, using `xpress` efficiently with `linopy` models requires setting solver parameters:
```
solver_options:
  xpress-default:
    THREADS: 8  # use 0 for unlimited
    LPFLAGS: 4  # barrier
    CROSSOVER: 0  
    BARALG: 2
```

The settings were suggested by FICO Xpress technical support and they are fine with me contributing them. The settings are fairly generic for `linopy` models. 

I can open a PR if you like.
